### ISSUE TITLE
Volume Lock

### ISSUE THREAD

**Issue by jise** [seht/volumenotification#10]
I am using [Volume Lock](https://play.google.com/store/apps/details?id=ezturner.volumelock) for locking Alarm, Media, and Ringtone volumes. But this literally one button app has size of 10MB when installed on my phone with Android 6.0.1!
It will be immensely useful if its function could be incorporated into your app. But please not by increasing its size by whopping 10MB of course :)

**Comment by seht** [comment]
Thank you for the suggestion. It will be looked into! 👍

**Comment by seht** [comment]
There's an app for that! :-) heh
Thank you for suggesting. Perhaps at some point I'll look at providing an API to other apps.
