### ISSUE TITLE
Bluetooth volume

### ISSUE THREAD

**Issue by jise** [seht/volumenotification#11]
I am looking forward to adding support for Bluetooth volume as I am wearing BT headset all day long.
I've used [Volumizer](https://play.google.com/store/apps/details?id=com.mithrandir.audio) for this purpose and for quick checking all volumes, but I prefer your elegant little app because it has no ads, is much smaller and is configurable.

**Comment by seht** [comment]
Thank you for suggesting. This will be coming soon! 👍

**Comment by jise** [comment]
I am using this enhancement now in version 0.9.4.1.
Thank you very much!

**Comment by seht** [comment]
Sweet.
