### ISSUE TITLE
Integration with Tasker (Enhancement Request)

### ISSUE THREAD

**Issue by Meyer20171** [seht/volumenotification#12]
It would be very, very helpful to me if I could enable and disable the notification using Tasker.  Tasker provides a facility to control 3rd party apps in this way, if the app is coded to allow it.

**Comment by seht** [comment]
Thank you for the suggestion! I shall look into this. 👍

**Comment by Meyer20171** [comment]
Thanks!

**Comment by jise** [comment]
@Meyer20171, please could you post your scenario how you will benefit from enabling/disabling Volume notification by Tasker? I am just curious and Tasker user too :)

**Comment by Meyer20171** [comment]
The app, Volume Notification, isn't something I need all the time. I have various tasker profiles that set my desired volume levels for places I frequent, such as home and work. So when I'm in those locations, I would prefer to not display the notification from this app (I've got too many always-on notifications already). 

But when I'm not in those locations, I want to turn on the volume notification, so I can quickly make adjustments. I drive a convertible, so the app is really handy to raise or lower volumes depending on whether the top is up or down.

**Comment by jise** [comment]
I see your reason clearly now. Thank you very much!

I am glad that I have two permanent notifications from AccuBattery and Weather app, so I have the notification from VU with lowest priority on the bottom of the screen just next to my thumb finger on my 5.5" display :)
![screenshot_2017-02-09-17-48-37](https://cloud.githubusercontent.com/assets/6588902/22793448/2977496c-eef0-11e6-90fe-15baa93cc282.png)

**Comment by seht** [comment]
I've exposed a foreground service, it's a step closer! :-)

**Comment by seht** [comment]
i'm planning an update to include a tile feat that opens App LInks / Urls . That should also solve this, although this apps's notification has been deprecated - it will only support tiles - moving fwd. thanks again for your contribution
