### ISSUE TITLE
Enable Notification doesn't work as expected

### ISSUE THREAD

**Issue by praveenmaddala** [seht/volumenotification#14]
I have been using this app on Lenovo k6 power and Redmi 3s Prime. No issues on Lenovo. On Redmi it doesn't​ work

**Comment by praveenmaddala** [comment]
I have been using this app on Lenovo k6 power and Redmi 3s Prime. No issues on Lenovo. On Redmi it doesn't​ work as expected. The notifications bar is disabled as soon as we quit the application.. seems like it's not working in background

**Comment by praveenmaddala** [comment]
Video link

https://drive.google.com/file/d/0B4mtf6CxGx-ASUFJVW9qcnlHbGs/view?usp=drivesdk

**Comment by seht** [comment]
I've not been able to reproduce this issue unfortunately. Please let me know if this update fixed it for you. Thank you!

**Comment by praveenmaddala** [comment]
Problem is resolved now, by enabling auto-start on boot, thanks for the reply.

"Volume Notification" is one of my favorite and most used app.
