### ISSUE TITLE
Doesn't work correctly on OnePlus 3

### ISSUE THREAD

**Issue by snafu88** [seht/volumenotification#16]
No matter what volume control I pick, be it notification, alarm, etc. It only displays and changes the "ring" volume. 
Running on Android 7.1.1.
I saw this demo'd on a Samsung S8 and the behavior on my OnePlus 3 is just not the same at all.

**Comment by seht** [comment]
The ring, notification and system volumes point to the same volume control on most devices. Could you confirm that this is not the case for media or alarm volumes? Thank you

**Comment by seht** [comment]
This should've been fixed now.
Closing after deploying the first stable release. Enjoy 1.0.1 :-)
Please reopen if you find this issue again. Thank you!
