### ISSUE TITLE
Quick Settings Buttons Stop Working

### ISSUE THREAD

**Issue by citizen2048** [seht/volumenotification#17]
Phone: Galaxy S8
Rooted: No
App version: 0.9.4.1

Issue:

After a restart or shutdown the quick setting buttons stop working. You have to remove them, open the app and toggle each one off / on and then go back to quick settings and add the buttons back.

**Comment by citizen2048** [comment]
Forgot to add app veesn: 0.9.4.1

**Comment by seht** [comment]
Thank you for reporting. Please check again with this update.

**Comment by citizen2048** [comment]
Sorry, same issue after update.

Not sure if it helps narrow things down but the quick settings buttons must be removed from the pulldown before toggling in the app.

Leaving them on the pulldown and togglimg them does not activate them. It seems the phone does not recognise the installation of settings buttons at startip.

**Comment by Asima13** [comment]
I'm commenting to agree with Citizen2048.. Quick settings don't work, at all for me even after removing... This all happened because I had to restart my phone. :/

**Comment by seht** [comment]
This should've been fixed now.
Closing after deploying the first stable release. Enjoy 1.0.1 :-)
Please reopen if you find this issue again. Thank you!
