### ISSUE TITLE
App icon

### ISSUE THREAD

**Issue by silentgurdian** [seht/volumenotification#18]
Could you remove the icon from the drawer and add a settings shortcut directly in the notification? I think it would be more convenient to adjust settings directly from the notification.

**Comment by jise** [comment]
This is absolutely unnecessary request:
1) You could hide app icon in drawer in your Launcher. It is much better if this decision is up to you and under your control and not depending on another person.
2) Settings shortcut is already here. Just long press app notification. Notice that for example for my configuration there is not any free space for your idea...
![screenshot_2017-08-16-11-50-36](https://user-images.githubusercontent.com/6588902/29358113-3b4c0218-827a-11e7-82a3-5eb1826ef0c2.png)
![screenshot_2017-08-16-11-54-16](https://user-images.githubusercontent.com/6588902/29358114-3b550fb6-827a-11e7-92e8-5bda5444de5b.png)

**Comment by silentgurdian** [comment]
Yeah, its more of a visual thing than functionality for me actually. The icon doesn't go well with most of the material design icons in the drawer, and I can't hide it in my stock launcher so I thought this could be a possible alternative. I wish get a better looking icon for it from someplace. Thanks for the suggestions though.

**Comment by jise** [comment]
I see your point now :)
I recommend to add hiding icon from the app drawer as an option anyway.
Workaround: What about make a folder in the drawer and "hide" such an icon here?

**Comment by seht** [comment]
Thank you for the feedback as always. Yes, there's not a lot that can be done unfortunately. However on newer phones this may now be possible with the next update. Please let me know!

**Comment by seht** [comment]
Not a lot that can be done on this one for now.
Closing after deploying the first stable release. Enjoy 1.0.1 :-)
Please reopen if you find this issue again. Thank you!
