### ISSUE TITLE
 Error opening Notification settings

### ISSUE THREAD

**Issue by Vazkeron** [seht/volumenotification#2]
Hi! My name is Abraham, your app worked awesome before, but now i don't know why, it don't let me open Notification settings.
My device is a Meizu M3 Note, with Android 5.1 Lollipop. Keep doing good work and upgrading your app! (Sorry for my english, i'm spanish xd)

**Comment by seht** [comment]
Grettings Abraham,

Thank you for reporting. I've just pushed a hot fix! Please check back and confirm it's working for you.

Thank you!

**Comment by Vazkeron** [comment]
Yep! It works now! You fixed it so quickly, good work Seht, thank you and keep doing it great like now! See you!

**Comment by seht** [comment]
Thank you! It's always good to hear! :)
