### ISSUE TITLE
Feature request: Notification Height 

### ISSUE THREAD

**Issue by VRanger** [seht/volumenotification#21]
I'm using MIUI and the notification height is too big. Please add an option to control the height of notification. /https://imgur.com/a/ffoar/
Thank you

**Comment by jise** [comment]
I think that it's not app problem in MIUI, but app problem with newest Android versions. What's your Android version?

**Comment by pao0j** [comment]
Would love this customizability as well. I'm on S8+ running Oreo

**Comment by seht** [comment]
If reduced the notification height with this update. I will try making it configurable on the next one. Please do try using quick settings tiles if you're running Android 7.0 or greater and your phone's launcher is compatible. I've noticed that previous versions of MIUI wouldn't allow apps service tiles.
