### ISSUE TITLE
App force close with DND

### ISSUE THREAD

**Issue by ems170** [seht/volumenotification#22]
Android 9
Not rooted
Ver 0.9.5
Pixel 3

App works great, when do not disturb is active the quick settings will cause the program to force close. This is reproducible and stops when dnd is deactivated.

**Comment by seht** [comment]
Have you tried disabling the behavior toggles on the app settings? Also let me know if this last update fixed it for you.

**Comment by seht** [comment]
This should've been fixed.
Closing after deploying the first stable release. Enjoy 1.0.1 :-)
Please reopen if you find this issue again. Thank you!
