### ISSUE TITLE
Not launching on startup

### ISSUE THREAD

**Issue by CreepyHobo** [seht/volumenotification#23]
I have a LG Stylo 4 running Android 8.  Even though I have set to load on startup it doesn't.

**Comment by seht** [comment]
Are you running this app on sd storage? Also if you're using Android 8 please consider using the quick settings tiles provided by the app. Let me know if this works for you.

**Comment by seht** [comment]
Closing after deploying the first stable release. Enjoy 1.0.1 :-)
Please reopen if you find this issue again. Thank you!
