### ISSUE TITLE
Wrong icons at notification bar on Huawei

### ISSUE THREAD

**Issue by sinusx1986** [seht/volumenotification#25]
Phone Huawei p20 lite. 
Android 8. Emui 8.0.0

After install icons at notification bar look properly, but after few hours they changed to blank white circles, but functional works as expected. 

![Screenshot_20190514-134838](https://user-images.githubusercontent.com/7704641/57692356-3d08ed80-764f-11e9-8255-c89152e80ce8.jpg)

**Comment by seht** [comment]
Thank you for reporting. That is strange. I wasn't able to reproduce this however you should be able to use quick settings tiles instead as recommended for newer phones. Please let me know if it works for you.

**Comment by seht** [comment]
Also, have tried switching the theme, or disabling transparency?

**Comment by seht** [comment]
Closing after deploying the first stable release. Enjoy 1.0.1 :-)
