### ISSUE TITLE
Please also include v1 signature

### ISSUE THREAD

**Issue by IzzySoft** [seht/volumenotification#26]
The APK attached to the recent version (v0.9.7) seems to be signed v2-only – it lacks the JAR signatures:

```bash
$ apksigner verify app-release.apk 
DOES NOT VERIFY
ERROR: No JAR signatures
```

This specifically means the minVer of 4.1 is "useless", as users on Android 6 or below cannot install/update the app anymore (correct me if I'm wrong, but AFAIR v2 was introduced with Nougat).

So may I kindly request you sign it both, v1+v2? If you use Android Studio, just make sure both check-boxes are ticked. Thanks!

**Comment by seht** [comment]
Yes sir! :-)
It's now been replaced by v0.9.8. Have fun and thank you for raising the issue.

**Comment by IzzySoft** [comment]
That was fast – if anything ever was! Thanks in the name of all your users still sitting on devices which no longer receive updates! :green_heart:

**Comment by seht** [comment]
Thanks Izzy. Your feedback is much appreciated. There's already a hot-fixed 0.9.9.1. :-) I'm wondering why the update propagation is taking so long -- it used to be quite speedy. It's been quite a huge gap in SDK versions but other than that the only difference is that I've uploaded this version in the new app bundle format... 🤔 Many thanks!

**Comment by IzzySoft** [comment]
Which update propagation do you refer to? The update checker for my repo runs all 24 hours and should push updates shortly before 7 pm UTC. In the official F-Droid repo it always takes a bit longer as manual steps are involved (signing takes place offline).

**Comment by seht** [comment]
I mean, it used to take a less time for every new release to be available on the Google Play Store. (Since I'd pushed one yesterday that it must have been queued for close to 24 hours, although it's not all that bad since I've release a of couple updates already.) Hopefully it will be live soon!

**Comment by IzzySoft** [comment]
Uh, *there.* I stopped using Play Store years ago; my phones even no longer have GApps installed. Your update should show up [here](https://apt.izzysoft.de/fdroid/index/apk/net.hyx.app.volumenotification) in about 12h (the previous one failed for above mentioned reasons, as even fdroidserver rejected it due to missing v1 signatures) – ah say what, I just triggered the sync manually so it should show up in a few minutes.

My repo can be used with the F-Droid client. And if you wish, we can bring your app to the official repo by filing an [request for packaging](https://gitlab.com/fdroid/rfp/issues): looks like it meets all requirements. You can do that yourself – I gladly assist if you wish (disclosure: I'm one of the maintainers there).

**Comment by seht** [comment]
Sweet. Nice initiative. Congrats. And I might do, should be releasing v1.0 soon. It's a shame Ubuntu phone didn't pick up after over a third of the $32m pledge... I'm pretty much tied to GSuite at the moment let alone GApps... :-( There were some AOSP projects like Cyanogenmod but it's hard[ware] to pick up heh

**Comment by IzzySoft** [comment]
Just let me know should you require my assistance.

And yeah, I'm on "LineageOS for microG" with my devices. microG offers an open source replacement for many Google APIs, often even replacing the GServices behind them (e.g. pretending to be Google Maps, but serving OSM behind the scenes) or using stubs for unwanted stuff (e.g. Analytics). If you want to, you can even have GCM with it (which I didn't enable, having cut my ties to Google quite completely). New devices I of course chose by LOS' compatibility list :wink:

**Comment by seht** [comment]
I'm seriously going to look into this (once I get a tablet or something for the worst cases heh).
Thank you heaps!
