### ISSUE TITLE
Issue running on Android 14 (forcing os separation of ring / notification stream type)

### ISSUE THREAD

**Issue by JiadyHu** [seht/volumenotification#28]
Due to Android 14 separating the ringtone volume from the notification volume, the "notification volume" function in the APP does not work now. This is a problem I discovered after upgrading to Android 14. I hope it can be fixed. Thank you to the development team for their efforts.

**Comment by seht** [comment]
this is oem os dependent unfortunately. the following update wont be able to fix this. thank you for raising this
