### ISSUE TITLE
Toggle ringer mute

### ISSUE THREAD

**Issue by seht** [seht/volumenotification#3]
Feature request received.

**Comment by pdutina** [comment]
This is very useful feature.. Great!

**Comment by seht** [comment]
This may not currently work on all devices (I have avoided to toggle silent mode due to permission requirements for Android 6.0+ i.e. setRingerMode(RINGER_MODE_SILENT)). This may have to be revisited.

**Comment by pdutina** [comment]
So it will not work on Nexus 5X, android 7.1.1 without new permission?

**Comment by seht** [comment]
Nexus 5X, should do with this update. Please let me know otherwise. Thanks!

**Comment by pdutina** [comment]
It is working, and it is working great :)

p.s. while in mute state, user can forget about that because there is not any visual mute indicator.
  It will be useful, ofcourse, if it is possible to make.

**Comment by seht** [comment]
That's great! :) A visual indicator as in changing the buttons wouldn't at the moment allow for the best implementation (since the mute could be triggered externally and it would be difficult to sync in real time without draining battery). However setting silent mode usually displays a status icon and I'm working on implementing this for Android 6.0, requiring that permission on request, that should be preferable. Lastly at some point will implement custom overlaying sliders and doing so would allow it to stay consistent with toggling the icons, and even displaying the current volume level under the icon. Thank you for the feedbak! :)
