### ISSUE TITLE
app crashes when I open it

### ISSUE THREAD

**Issue by bluelupo** [seht/volumenotification#30]
Hi seht,
I installed the new version 1.1.0-beta1 of your app "Volume Notification" today. Unfortunately, the app crashes when I open it. However, the previous version 1.0.7-alpha3 works correctly. The version before last, 1.06.3-alpha2, also worked. If you need more information I can send it to you.

My hardware:

Oneplus 8 (IN2013)

Android version 13

What can I do to ensure that the latest version runs on my hardware?

Regards

Michael

**Comment by seht** [comment]
Please try reinstalling. Thank you!
