### ISSUE TITLE
appearing time set for appeared controls

### ISSUE THREAD

**Issue by DI555** [seht/volumenotification#31]
it would be great if be possible to adjust appearing time setings for appeared controls, so will be no moments when appeared needed vol.control already dissappeared((
great if it’ll be for each type of controls, to separately each adjustment!!!

many thanks in advance!

**Comment by seht** [comment]
Unfortunately this is out of scope. I have no control over the time that system controls are displayed. It would require custom controls that are out of scope. Thank you for the suggestion! I wish I could! AFAIK, this is not possible.
