### ISSUE TITLE
an option be always appeared "on" of control untill another press the button

### ISSUE THREAD

**Issue by DI555** [seht/volumenotification#32]
i’d like to ask for an option "always appeared "on" of control untill another press the button", it will be very useful for medea players, etc., - when needed always to andjust the volume but switch anothee time the button to turn off the control slider.

and like an idea, be great if it works "on" and "off" by the long press the same widget button! 
- so it’ll trigger be always on or off the needed vol.adgust slider by a long press on-the-fly!!!

**Comment by seht** [comment]
Not sure I understand exactly what you're suggesting but I've added a feature where tiles can now be toggled as on or off! Let me know if this works for you.
