### ISSUE TITLE
Translating to Spanish

### ISSUE THREAD

**Issue by Vazkeron** [seht/volumenotification#7]
How can i help you with the spanish translation? I could help you!

**Comment by seht** [comment]
Hey Vazkeron. Thank you for your interest. It's pretty easy. All it requires is translating this file:
https://github.com/seht/volumenotification/blob/master/app/src/main/res/values/strings.xml
(to the folder ../values-es/ and submitting a pull request! Or just sending it to my email and I'll add the file and attribution). Thank you!

**Comment by Vazkeron** [comment]
Hey Seht! I posted an update of the file bcz i don't know how to create a folder and post it, have you seen ir? If not, how can i do It?

**Comment by seht** [comment]
Hey no problem at all. Just send it over to my email if it makes it easier for you. Also include a link to your page or such so that I can attribution if you'd like. Thank you!

**Comment by seht** [comment]
You would have to create a pull request for me to see it. Anyway, you don't need to bother with that, if you don't have to. :)

**Comment by seht** [comment]
Please reopen if you're able to collaborate with translation. Thank you!
Just released v1.0! :-)
