### ISSUE TITLE
Option for showing all other volumes

### ISSUE THREAD

**Issue by jise** [seht/volumenotification#9]
What about adding a cog icon too for showing all other volumes so we don't need to reach the system cog icon in upper right corner.

Or another approach:
Add an option when you click on the same volume icon more than once, then all other volumes will roll out down. It'll collide with Toggle mute/silent for some users, so in that case they should disable both mute options with this double click option enabled probably.

**Comment by seht** [comment]
Thank you for the suggestion! I shall look into this.

**Comment by seht** [comment]
As Android evolves the harder it's becoming. However I'm still planning on developing a "custom overlay" for sliders (which would however require the permission to draw over other apps)...
